AB#141773 Sdk Create Sample Record
NIPOSoftwareBV/Nfield-SDK pull request #468
Opened 2024-01-17 15:55 UTC by jlKampos

[AB#141773](https://dev.azure.com/niposoftware/15ce0e91-931d-4fbf-9169-8c3dde412b54/_workitems/edit/141773)

NOTE: not sure how to increment the version number

2024-01-18 15:19 UTC, AlbertoBelver requested changes

2024-01-18 15:19 UTC, AlbertoBelver commented on Library/Services/INfieldSurveySampleService.cs
> +        Task<IEnumerable<SampleColumnCreate>> CreateSampleRecord(string surveyId, IEnumerable<SampleColumnCreate> sampleColumns);
```suggestion
        Task<IEnumerable<SampleColumnCreate>> CreateAsync(string surveyId, IEnumerable<SampleColumnCreate> sampleColumns);
```

2024-01-18 15:19 UTC, AlbertoBelver commented on Library/Services/INfieldSurveySampleService.cs
> +        /// Creates custom columns for the specified record in the survey
not only custom columns
```suggestion
        /// Creates a single sample record with the specified columns
```

2024-01-18 15:19 UTC, AlbertoBelver commented on Library/Services/INfieldSurveySampleService.cs
> +        /// <returns></returns>
Add the returns description

2024-01-18 15:19 UTC, AlbertoBelver commented on Library/Services/Implementation/NfieldSurveySampleService.cs
> +        public async Task<IEnumerable<SampleColumnCreate>> CreateSampleRecord(string surveyId, IEnumerable<SampleColumnCreate> sampleColumns)
```suggestion
        public async Task<IEnumerable<SampleColumnCreate>> CreateAsync(string surveyId, IEnumerable<SampleColumnCreate> sampleColumns)
```

2024-01-19 08:40 UTC, jlKampos commented on Library/Services/Implementation/NfieldSurveySampleService.cs
> +        public async Task<IEnumerable<SampleColumnCreate>> CreateSampleRecord(string surveyId, IEnumerable<SampleColumnCreate> sampleColumns)
done

2024-01-19 08:41 UTC, AlbertoBelver approved these changes

2024-01-19 08:41 UTC, AlbertoBelver commented on Library/Services/INfieldSurveySampleService.cs
> +        /// <returns>Returns the list of created columns and their values</returns>
```suggestion
        /// <returns>Returns the full columns set and their values for the created sample record</returns>
```

2024-01-19 09:10 UTC, merged